INSERT INTO OPER_OPERATOR(ID,,LOGINNAME,PASSWORD,USERNAME)
	values('123456','admin','admin','admin');
INSERT INTO OPER_OPERATOR(ID,LOGINNAME,PASSWORD,USERNAME)
	values('123456001','yr','yr','yr');
INSERT INTO OPER_OPERATOR(ID,LOGINNAME,PASSWORD,USERNAME)
	values('123456002','pqy','pqy','pqy');
commit;
