drop table if exists LA_LOAN_ACCOUNT;
create table LA_LOAN_ACCOUNT(
	id varchar(64) not null comment '主键ID',
	category varchar(64) not null comment '分类',
	loanAccountType varchar(64) not null comment '贷款帐户类型',
	contractId varchar(64) comment '贷款合同ID',
	contractNumber varchar(64) comment '合同编号',
	effectiveDate datetime comment '生效时间/合同起始日期',
	expiryDate datetime comment '到期时间/合同结束日期',
	loanAmount decimal(16,2) not null comment '贷款金额',
	totalPeriod integer not null comment '总期数',
	paidPeriod decimal(16,8) not null comment '已付期数',
	interestDate datetime not null comment '计息日--通常==实际放款日',
	factLoanDate datetime not null comment '实际放款时间',
	factOutLoanAmount decimal(16,2) not null comment '实际放款金额',
	repayWay varchar(64) not null comment '还款方式',
	timeUnitType varchar(64) not null comment '时间单位',
	time integer not null comment '时间',
	clientId varchar(64) comment '对应客户ID',
	clientIdCardType varchar(64) not null comment '证件类型',
	clientIdCardNumber varchar(64) not null comment '证件号码',
	clientName varchar(64) not null comment '客户名称',
	clientAccountId varchar(64) comment '对应客户账户ID',
	creditInfoId varchar(64) not null comment '客户信用信息ID',
	creditInfoVersion varchar(64) comment '信用信息Tag版本',
	sourceLastTradingRecordId varchar(64) comment '原贷款账户最后一笔交易记录ID',
	sourceLoanAccountId varchar(64) comment '原贷贷款账户id',
	beforeDelayDays integer not null default 0 comment '贷前延期天数',
	afterDelayDays integer not null default 0 comment '贷后延期天数',
	accountStatus varchar(64) not null comment '帐户状态',
	collectionStatus varchar(64) not null comment '催收状态',
	closed bit not null default 0 comment '是否关闭XX',
	died bit not null default 0 comment '是否死亡DA',
	legalProcedure bit not null default 0 comment '是否法律程序LP AC/DQ/DA/LP/XX',
	settleInterestStatus varchar(64) not null comment '结息状态',
	locked bit not null default 0 comment '是否锁定',
	lastLockDate datetime comment '最后一次锁定时间',
	inHisTable bit comment '是否历史账户',
	existNotReceivedTrading bit not null default 0 comment '是否存在未到账交易',
	currentPeriod varchar(64) comment '当前期数',
	currentPeriodExpireDate datetime comment ' 当前期数到期日',
	firstRepayDate datetime comment '首期还款日期',
	monthlyRepayAmount decimal(16,2) comment '每月还款金额',
	monthlyRepayDay integer comment '每月还款日',
	graceDays integer comment '上次还款金额',
	lastRepayAmount decimal(16,2) comment '',
	lastRepayDate datetime comment '上次还款日',
	nextOverdueCheckDate datetime comment '最后逾期检测日 [保留字段] ',
	nextRepayDate datetime comment '下次还款日期',
	nextDeductDate datetime comment '下次还款日期',
	nextSettleInterestDate datetime comment '下次结息日',
	overRepayAmount decimal(16,2) comment '超额还款金额',
	outsource bit comment '委外是否发生过',
	outsourceHappend bit comment '是否正在发生委外',
	outsourceAssignRecordId varchar(64) comment '委外分配记录ID',
	outsourceAmount decimal(16,2) comment '委外金额',
	outsourcePercentage decimal(16,8) comment '委外佣金比率',
	overdue bit comment '是否逾期',
	overdueDate datetime comment '逾期日期',
	overdueAmount decimal(16,2) not null comment '逾期金额（在现有业务中实际是为：逾期的 本金+利息+管理费 之和）',
	overdueSum decimal(16,2) not null comment '逾期金额总额（除逾期金额之外的费用，包括逾期利息）',
	principalBalance decimal(16,2) not null comment '本金结余',
	principalBalanceIrr decimal(16,2) not null comment '本金结余递减',
	revoked bit not null default 0 comment '是否退回',
	revokeDate datetime comment '退回时间',
	revokeReason varchar(500) comment '退回原因',
	settle bit not null default 0 comment '是否结清',
	settleCurrentPeriod varchar(64) comment '结清时对应的当前期数',
	settleDate datetime comment '结清交易发生日期',
	settleRepayDate datetime comment ' 结清交易发生日期',
	settleRepayDatePeriod varchar(64) comment '结清还款日对应的期数',
	settleSL bit not null default 0 comment '是否SL结清',
	settleSLDate datetime comment 'SL结清交易发生日期,SL结清时',
	settleSLRepayDate datetime comment 'SL结清交易发生的还款日期',
	settleSLRepayDatePeriod varchar(64) comment 'SL结清还款日对应的期数',
	writeOff bit not null default 0 comment '是否注销',
	writeOffAmount decimal(16,2) comment '注销金额',
	writeOffDate datetime comment '注销日期',
	writeOffReason varchar(500) comment '注销原因',
	writeOffRepayAmount decimal(16,2) comment '注销后还款金额',
	lastUpdateDate datetime not null default now() comment '更新时间',
	createDate datetime not null default now() comment '创建时间',
	vcid varchar(64) comment '贷款账户所属虚中心ID',
	districtId varchar(64) comment '区ID',
	organizationId varchar(64) comment '贷款账户所属组织ID[保留字段]',
	primary key(id)
);
create unique index IDX_LOAN_ACCOUNT_00 on LA_LOAN_ACCOUNT(contractNumber);
create unique index IDX_LOAN_ACCOUNT_01 on LA_LOAN_ACCOUNT(contractId);
create index IDX_LOAN_ACCOUNT_02 on LA_LOAN_ACCOUNT(createDate);
create index IDX_LOAN_ACCOUNT_03 on LA_LOAN_ACCOUNT(clientId);
create index IDX_LOAN_ACCOUNT_04 on LA_LOAN_ACCOUNT(clientAccountId);
create index IDX_LOAN_ACCOUNT_05 on LA_LOAN_ACCOUNT(creditInfoId,creditInfoVersion);
create index IDX_LOAN_ACCOUNT_06 on LA_LOAN_ACCOUNT(clientIdCardNumber,clientIdCardType);
