drop table if exists la_trading_record;
create table la_trading_record(
	id varchar(64) not null,
	requestId varchar(64) not null,
	sourceType varchar(64),
	loanAccountId varchar(64) not null,
	relatedTradingRecordId varchar(64),
	category varchar(64) not null,
	type varchar(64) not null,
	viewAble bit not null default 1,
	adjust bit not null default 0,
	repaySum decimal(20,6) not null,
	sum decimal(20,6) not null,
	bankAccountId varchar(64),
	repayDate datetime,
	repayDatePeriod varchar(64),
	currentPeriod varchar(64) not null,
	expireDate datetime,
	received bit,
	receiveDate datetime,
	writeOff bit not null default 0,
	writeOffDate datetime,
	beforeAccountStatus varchar(64) not null,
	beforeCollectionStatus varchar(64) not null,
	beforeIsClose bit not null,
	beforeIsDie bit not null,
	beforeIsLegalProcedure bit not null,
	beforePrincipalBalance decimal(16,2) not null,
	beforePrincipalBalanceIrr decimal(16,2) not null,
	beforeSettleInterestStatus varchar(64) not null,
	beforeIsOverdue bit not null,
	beforeOverdueAmount decimal(16,2) not null,
	beforeOverdueSum decimal(16,2) not null,
	beforeOverdueDate datetime,
	afterAccountStatus varchar(64) not null,
	afterCollectionStatus varchar(64) not null,
	afterIsClose bit not null,
	afterIsDie bit not null,
	afterIsLegalProcedure bit not null,
	afterPrincipalBalance decimal(16,2) not null,
	afterPrincipalBalanceIrr decimal(16,2) not null,
	afterSettleInterestStatus varchar(64) not null,
	afterIsOverdue bit not null,
	afterOverdueAmount decimal(16,2) not null,
	afterOverdueSum decimal(16,2) not null,
	afterOverdueDate datetime,
	principalBalance decimal(16,2),
	principalBalanceIrr decimal(16,2),
	outsourceAssignRecordId varchar(64),
	outsourceRepay bit,
	revokeAble bit not null default 0,
	revoked bit not null default 0,
	revokeDate datetime,
	revokeResean varchar(500),
	revokeOperatorId varchar(64),
	summary varchar(500),
	attributes varchar(2000),
	remark varchar(2000),
	createDate datetime not null default now(),
	lastUpdateDate datetime not null default now(),
	lastUpdateOperatorId varchar(64),
	vcid varchar(64),
	operatorId varchar(64),
	organizationId varchar(64),
	primary key(id)
);
create index idx_la_trading_record_01 on la_trading_record(requestId);
create index idx_la_trading_record_02 on la_trading_record(loanAccountId);
create index idx_la_trading_record_03 on la_trading_record(relatedTradingRecordId);
create index idx_la_trading_record_04 on la_trading_record(outsourceAssignRecordId);
