drop table if exists oper_operator_ref_his;
CREATE TABLE oper_operator_ref_his(
	EFFECTIVEDATE datetime,
	CREATEDATE datetime not null,
	OPERATORID varchar(64) not null,
	REFID varchar(64) not null,
	ENDDATE datetime not null,
	INVALIDDATE datetime,
	REFTYPE varchar(255) not null
);
CREATE INDEX IDX_OPER_OPERREF_HIS_00 ON OPER_OPERATOR_REF(OPERATORID,REFTYPE);
CREATE INDEX IDX_OPER_OPERREF_HIS_01 ON OPER_OPERATOR_REF(REFID,REFTYPE);
CREATE INDEX IDX_OPER_OPERREF_HIS_10 ON OPER_OPERATOR_REF(OPERATORID,REFID,REFTYPE);
CREATE INDEX IDX_OPER_OPERREF_HIS_02 ON OPER_OPERATOR_REF(INVALIDDATE);
