ALTER TABLE ORG_ORGANIZATION ADD CONSTRAINT FK_ORGANIZATION_01 FOREIGN KEY(parentId) REFERENCES ORG_ORGANIZATION(id);
ALTER TABLE ORG_ORGANIZATION ADD CONSTRAINT FK_ORGANIZATION_02 FOREIGN KEY(vcid) REFERENCES VC_VIRTUAL_CENTER(id);
