--****************************************************************************
-- 人员引用表：负责处理人员关联角色，关联分组，等关联关系：OPER_OPERATOR
--****************************************************************************
DROP TABLE OPER_OPERATOR_REF;
CREATE TABLE OPER_OPERATOR_REF(
	OPERATORID VARCHAR2(64) NOT NULL,
	REFID VARCHAR2(64) NOT NULL,
	REFTYPE VARCHAR2(64) NOT NULL,
	CREATEDATE DATE DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY(OPERATORID,REFID,REFTYPE)
);
CREATE INDEX IDX_OPER_OPERREF_00 ON OPER_OPERATOR_REF(OPERATORID,REFTYPE);
CREATE INDEX IDX_OPER_OPERREF_01 ON OPER_OPERATOR_REF(REFID,REFTYPE);
